spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  data:
    mongodb:
      database: xc_cms
      uri: mongodb://localhost:27017

server:
  port: 31000


